### ISSUE TITLE
Question on the Example

### ISSUE THREAD

**Issue by Melonbwead** [tgardner/cordova-androidwear#1]
Do i need to do anything on the Android Wear Smartwatch for the example to work?

So far i build this on my phone device, and it seems to be fine for `onConnect` where i can see the alert, but `onDataReceived` isn't being triggered. The smart watch has dev mode turned on and its paired with the phone as well.

**Comment by tgardner** [comment]
Yes, you need to build a watch app that sends data.

**Comment by 9killua9** [comment]
Have an example app for watch ?

**Comment by brilvio** [comment]
Hi I can connect, and I can send message but the message does't appear on the watch.
