### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by dayaki** [tgardner/cordova-androidwear#11]
Just wondering if this project is still active? if Yes, plans for wear 2.0?

**Comment by ragcsalo** [comment]
It works well with Wear 2.0 :-)
Here is my fork with Google Play Services v11.8.0 compatibility:
[https://github.com/ragcsalo/cordova-androidwear](https://github.com/ragcsalo/cordova-androidwear)

**Comment by tgardner** [comment]
Didn't think so, but apparently found some time. Wear 2.0 support should be in once #12 is complete.
