### ISSUE TITLE
NodeApi and MessageApi deprecated, can't build APK

### ISSUE THREAD

**Issue by ragcsalo** [tgardner/cordova-androidwear#12]
ERROR in WearProviderService.java (lines 24, 25 and more):

com.google.android.gms.wearable.NodeApi is deprecated
com.google.android.gms.wearable.MessageApi is deprecated

NodeApi: This interface was deprecated. Use NodeClient instead!
MessageApi: This interface was deprecated. Use MessageClient instead!

#tgardner please update the plugin! Thanks! :-)

**Comment by ragcsalo** [comment]
If anyone could make a usable fork, please do it!!! I couldn't find any other AndroidWear plugin... shame....

**Comment by ragcsalo** [comment]
After 2 days of searching, I finally found a solution (although I'm a beginner in coding Java). :-)
Here is my fork, which works with the latest Google Play Services (v11.8.0):
[https://github.com/ragcsalo/cordova-androidwear](https://github.com/ragcsalo/cordova-androidwear)

**Comment by TwanoO67** [comment]
Nice :) Could you do a Pull Request for that ?

**Comment by ragcsalo** [comment]
I think #tgardner has not been updating the plugin for 2 years now... I contacted him but no response yet. :-/

Update: welcome back, @tgardner :-)))))))

**Comment by tgardner** [comment]
Hey @ragcsalo , if you've written a fix for the issue, I'll happily accept a PR for it. Please send it through so I can take a look. Cheers

**Comment by ragcsalo** [comment]
Dear @tgardner :-) Please take a look at my fork: [https://github.com/ragcsalo/cordova-androidwear](https://github.com/ragcsalo/cordova-androidwear)
The only file I had to modify is [src/android/WearProviderService.java](https://github.com/ragcsalo/cordova-androidwear/blob/master/src/android/WearProviderService.java)
You can copy it to your release :-)

The MessageApi is also deprecated, but looks like it still can be used for a while... but if you're good at Java coding, you could replace it with the MessageClient class. Here is the release note of the latest Google Play Services, which mentions the deprecation of some Wearable classes:
[https://developers.google.com/android/guides/releases](https://developers.google.com/android/guides/releases)

**Comment by tgardner** [comment]
Hi @ragcsalo, no point merging something that is already deprecated. I had a look at it this morning, and adjusted for the MessageClient implementation. Also noticed that the GooglePlayApi was deprecated in favour of the CapabilityClient.
Can you take a look at https://github.com/tgardner/cordova-androidwear/tree/dev and tell me if that fixes your issue? Note the breaking change mentioned in the README. I created a dev branch on the example project too if you're unsure of anything.

Let me know and I'll merge it, cheers.

**Comment by ragcsalo** [comment]
Thanks for the update! :-)
Unfortunately I get multiple errors when building the APK in Android Studio.

AndroidWearPlugin.java (line 29):
Cannot resolve symbol 'WearMessageApi'
Cannot resolve symbol 'WearMessageListener'

In multiple lines:
Lambda expressions are not supported at this language level
Diamond types are not supported at this language level
Method references are not supported at this language level

Have you tried to build the APK in Android Studio?

**Comment by tgardner** [comment]
Hi @ragcsalo, I wrote it in Android Studio. I'm guessing you're on Java 1.7 or lower. I've updated the branch, so it should be backwards compatible. Please pull down the latest and try again. Thanks

**Comment by ragcsalo** [comment]
Thanks, it builds now without errors. :-)

I've added the messaging capability resource to the watch app (wear.xml),
but it doesn't work yet... do I have to change the Java code of the watch
app as well?

**Comment by tgardner** [comment]
The message path has changed to "/NewMessage". Failing that, take a look at the example project at https://github.com/tgardner/cordova-androidwear-example/tree/dev

**Comment by ragcsalo** [comment]
Thanks, I will try soon. :-)

Would it be difficult to include the possibility to send data with the
DataApi? We could send assets like images to the watch... it would be
great!!!! :-)

**Comment by tgardner** [comment]
Maybe in the future, I'm very time poor at the moment. Feel free to take my example of the MessageClient and CapabilityClient implementations, and apply it to the DataClient as well. Always welcome pull requests :)

**Comment by tgardner** [comment]
Fixed in 1.0.1
