### ISSUE TITLE
Cannot Find Symbol error with 1.0.1

### ISSUE THREAD

**Issue by skwerlzu** [tgardner/cordova-androidwear#13]
Getting build errors as follows:

Severity	Code	Description	Project	File	Line	Suppression State
Error		....\WearProviderService.java:16: error: cannot find symbol	
Severity	Code	Description	Project	File	Line	Suppression State
Error		import com.google.android.gms.wearable.CapabilityClient;	

Getting the same error for all com.google.android.gms.wearable imports

Environment Setups
Windows 10
Cordova 8
Android 7
minimum sdk 23
target 26
All android packages for sdk 24 up are installed

Let me know if you have seen this or if you need more information from me. I can't share a ton on the app I am developing. Am under NDA.
[error log.txt](https://github.com/tgardner/cordova-androidwear/files/1650758/error.log.txt)

**Comment by tgardner** [comment]
Can you please try setting the target SDK to >=26
I believe wear 2 support requires it.

What version build tools are you using?

Also, have you got Google Play Services installed via the SDK manager?

**Comment by skwerlzu** [comment]
Cordova V8
Visual Studio 17
Android SDK Build Tool 27.0.3
Platform tools  27.0.1

Set target and minimum sdk to 26

Attached the error log
[error log 2.txt](https://github.com/tgardner/cordova-androidwear/files/1680278/error.log.2.txt)

Let me know if you need anything else from me. More than glad to help in anyway

**Comment by tgardner** [comment]
The error is in relation to missing google classes.

What version of Google play services do you have installed?

![image](https://user-images.githubusercontent.com/778456/35604166-d56054fe-0690-11e8-88f6-7d597699fcbb.png)

**Comment by skwerlzu** [comment]
![image](https://user-images.githubusercontent.com/12980656/35604621-aa618ab2-0608-11e8-8478-2f035b8d20fe.png)

**Comment by tgardner** [comment]
Can you please confirm that the following is listed in your app build.gradle dependencies?

```
    compile "com.google.android.gms:play-services-base:+"
    compile "com.google.android.gms:play-services-wearable:+"
```

**Comment by skwerlzu** [comment]
![image](https://user-images.githubusercontent.com/12980656/35605154-6eae9100-060c-11e8-96f1-589be7a982fd.png)
![image](https://user-images.githubusercontent.com/12980656/35605175-93d8dcc4-060c-11e8-8d03-52fc45fa0537.png)

**Comment by skwerlzu** [comment]
Sorry if the notepad image is blurry, doing a direct paste

**Comment by skwerlzu** [comment]
Would a full version of the build gradle help?

**Comment by tgardner** [comment]
You have multiple declarations of com.android.support:support-v4 
Try deleting the lower versioned one. Clean and rebuild.

**Comment by skwerlzu** [comment]
Deleted it and it gets re added. Will have to check other plugin dependencies and see where the lower version is being set

**Comment by skwerlzu** [comment]
cordova-plugin-x-socialsharing and cordova-plugin-camera were both requesting 4:24.1.1+

Updated plugin code to 4:25.+

No errors related to the change, but it did have the desired effect of removing the duplicate/lower version android.support version from the build.gradle

Unfortunately I did receive the same errors as previously shared. "cannot find symbol"

Let me know if you you need any further files or environment info.

**Comment by tgardner** [comment]
If you create a blank project add this plugin, are you able to build successfully?
Need to determine if it's an issue with your environment, or a conflict with another plugin you have installed

**Comment by tgardner** [comment]
Actually your screenshot shows you're building against play services 11.0.4.
CapabilityClient wasn't added until 11.8.0. You need to bump your play services version.

https://developers.google.com/android/guides/releases#december_18_2017_-_version_1180

Change the + to 11.8.0 to the wearable dependencies. I'm guessing your maps plugin is forcing it to the lower version rather than the latest

**Comment by skwerlzu** [comment]
Sorry for this question, but for some reason my sdk is not recognizing play services 11.8 update and when including in gradle build I get "could not resolve" errors. Have you seen this before? 

I have searched every term and phrase I could think of to no avail.

**Comment by tgardner** [comment]
Are you including the google maven repository?
https://developer.android.com/studio/build/dependencies.html#google-maven

**Comment by skwerlzu** [comment]
Went head first down the rabbit hole with cleaning up compatibility issues, but I believe I got all the dependencies installed.

For others to reference if they are using Visual Studio, adding the maven url to dependencies worked. 
It needs to be added to the android gradle.build file in platforms/android directory of their project folder

Since visual studio 2017 seems to be particular on it's gradle build versions you have to add the actual url and cannot use google() until VS upgrades it's gradle build tool dependency above 3.0.0.

Once this was added it did recognize and download play services 11.8.0

Now, more of a question than an issue, but how does this work with a wear 2 app? From what I understand you cannot add another app on the google play store with the same package name. Does this still depend on the wear app having the same name?

**Comment by tgardner** [comment]
https://developer.android.com/training/wearables/apps/packaging.html
Multi apk releases

**Comment by skwerlzu** [comment]
You are a wealth of knowledge good sir. A scholar and a gentleman. Thank you for being so helpful with this. Very much appreciated.

I am just getting started on this, so I hope you don't mind if I have further questions upcoming.

**Comment by skwerlzu** [comment]
Hope all is well, I ran into another snag.

I had everything working, messages coming and going as expected, but had to do a full rebuild an am running into this error:
		..\platforms\android\src\net\trentgardner\cordova\androidwear\WearProviderService.java:25: error: cannot find symbol  NodeApi.NodeListener,

Getting this for all NodeApi calls. 

Play Services 11.8 installed
Google Support 25.+ installed (Without duplicate)
Gradle V: 3.0.0
MinSdk 25
Target Sdk 26


I'm just gonna include everything. Let me know if I have everything right..

[errorlog.txt](https://github.com/tgardner/cordova-androidwear/files/1691980/errorlog.txt)
[buildgradle.txt](https://github.com/tgardner/cordova-androidwear/files/1691981/buildgradle.txt)
[buildLog.txt](https://github.com/tgardner/cordova-androidwear/files/1691982/buildLog.txt)
