### ISSUE TITLE
Is there any complete example?

### ISSUE THREAD

**Issue by joshardt** [tgardner/cordova-androidwear#2]
I am very new to Android Wear and Cordova and therefore I unfortunately have to admit that I don't understand how to use this plugin. Is there any example project you can recommend to me? Just a really simple project to understand the basics would be great. Or maybe you have any tips where I can get some information to make Android Wear apps with Cordova? A blog entry or anything similar would be very much appreciated!

**Comment by ericvangeem** [comment]
I was just about to open up an issue with a similar question as I am also very curious, but you beat me to it. 

When I paste the provided sample code from the README into my Cordova app I can see the alert message "Connection Successfully Established" which is nice, but that's about as far as I've gotten so far. 

I have an existing Wearable app that I've modified to listen for incoming messages from this plugin using the `"net.trentgardner.cordova.androidwear.NewMessage"`message path. My Wear activity implements  the `MessageApi.MessageListener` interface and is listening for incoming messages in the `onMessageReceived` hook method, but for some reason I am not receiving these messages at all. 

I've checked the ADB logs and I see various error messages related to Google Play services such as this `E/GooglePlayServicesUtil﹕ The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.` however I definitely have the google play services cordova plugin installed just as this project's README says to do so.

Any further guidance from here, such as an example Wearable app that integrates with a cordova app, would be of great help.

**Comment by tgardner** [comment]
Hey guys,

I've put together a basic example that you can follow at https://github.com/tgardner/cordova-androidwear-example

Hope it helps.

Cheers,

Trent

**Comment by ericvangeem** [comment]
Thanks! In addition to `cordova platform add android` do I also need to add your plugin to the phone module via `cordova plugin add https://github.com/tgardner/cordova-androidwear.git`?

**Comment by tgardner** [comment]
It should pick it up automatically from the projects `config.xml` when adding the platform. 

Also the issue you're describing sounds like your watch apps package ID is different from your phone app. They need to be the same.

**Comment by joshardt** [comment]
Thanks a lot!
