### ISSUE TITLE
Where i have to add the java files 

### ISSUE THREAD

**Issue by chrissd23** [tgardner/cordova-androidwear#3]
Hi, 

ich would like to integrate your plugin in my project. So i have a existing android wear app. So after packing the app , i add the app to my cordova project. How can i use your plugin. Should i add the java classes to my wear project or to my nativ code in my cordova project.

**Comment by tgardner** [comment]
Hi @ChrisDolge,

Please see the example project at https://github.com/tgardner/cordova-androidwear-example

**Comment by chrissd23** [comment]
Thx , i should read the readme :)
