### ISSUE TITLE
sending and receiving messages problem

### ISSUE THREAD

**Issue by HerSaad** [tgardner/cordova-androidwear#5]
Hi  @tgardner  ,
Thank you for making this plugin .
The plugin have been installed successfully but I still not be able to send or receive any messages .
To test the plugin I have made a simple wear app witch shows the received messages and sends a simple String "Hello from Wear" to a simple cordova app ( with the path : "net.trentgardner.cordova.androidwear.NewMessage" ) .

this is my onDeviceReady function :

``` javascript
onDeviceReady: function() {
        app.receivedEvent('deviceready');

         AndroidWear.onConnect(function(e) {
      alert("Connection Successfully Established - handle: " + e.handle);

      AndroidWear.onDataReceived(e.handle, function(e) {
          alert("Data received - handle: " + e.handle + " data: "+ e.data);
      });

      AndroidWear.sendData(e.handle, "Hello From Cordova!");
  });

    }
```

After running the cordova app in my phone device I receive this Alert : ( Connection Successfully Established - handle : df58e11e )  witch means that the onConnect function has been successfully called . But in the wear app I don't receive anything and after sending the String from the wear app I don't receive also anything in the cordova app .

I would like to mention that the wear app is working without problems with another native android app .

Thanks in advance !

**Comment by tgardner** [comment]
Hi @HerSaad,

Have you tried taking a look at the sample project mentioned in the Readme? 

Also logcat may be able to enlighten you as to what is going on. 

Thanks, 

Trent

**Comment by HerSaad** [comment]
Hi @tgardner ,

Thank you a lot .
your project is working well .

Saad
