### ISSUE TITLE
Plugin add

### ISSUE THREAD

**Issue by Damirme** [tgardner/cordova-androidwear#6]
after executing cordova command: cordova plugin add
it give me the error:
Fetching plugin "net.trentgardner.cordova.androidwear" via cordova plugins registry
npm http GET http://registry.cordova.io/net.trentgardner.cordova.androidwear
npm http 200 http://registry.cordova.io/net.trentgardner.cordova.androidwear
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
Fetching from cordova plugins registry failed: connect ETIMEDOUT 173.192.57.105:80
Fetching plugin "net.trentgardner.cordova.androidwear" via npm
npm http GET https://registry.npmjs.org/net.trentgardner.cordova.androidwear
npm http 404 https://registry.npmjs.org/net.trentgardner.cordova.androidwear
TypeError: Cannot read property 'latest' of undefined
    at next (C:\Users\damir.mailybayev\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\lib\cache.js:687:35)
    at C:\Users\damir.mailybayev\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\lib\cache.js:675:5
    at saved (C:\Users\damir.mailybayev\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
    at C:\Users\damir.mailybayev\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by ragcsalo** [comment]
I could install it like this:
cordova plugin add https://github.com/tgardner/cordova-androidwear

**Comment by tgardner** [comment]
I'm guessing from the error `connect ETIMEDOUT 173.192.57.105:80` you were having internet connectivity issues.. Either that or the npm registry was having problems, I noticed you were receiving 404 errors on this line `npm http 404 https://registry.npmjs.org/net.trentgardner.cordova.androidwear`

I'm unable to reproduce any such error.
