### ISSUE TITLE
Plugin install FAILED, please fix bug!!!

### ISSUE THREAD

**Issue by ragcsalo** [tgardner/cordova-androidwear#7]
Please fix the plugin installation package!!!

Fetching plugin "net.trentgardner.cordova.androidwear" via cordova plugins regis
try
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.tren
tgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite
/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0
.3.tgz

**Comment by ragcsalo** [comment]
Oh, I could install it like this:
cordova plugin add https://github.com/tgardner/cordova-androidwear

So please update the documentation, and recommend this install method! :-)

**Comment by tgardner** [comment]
Duplicate of #6
