### ISSUE TITLE
Breaks Intel XDK's debug module builder

### ISSUE THREAD

**Issue by MichaelPaulus1** [tgardner/cordova-androidwear#8]
If I implement this as a cordova plugin in Intel XDK and try to renew the debug module, the builder states it fails, but fails to give a reason as to why.
Intel XDK does not provide a res/raw folder and as such can't bundle the packages as described in the documentation you linked.

**Comment by tgardner** [comment]
Could potentially package your application via the Wear 2.0 play console.
https://developer.android.com/training/wearables/apps/packaging.html#console
